/* ═══════════════════════════════════════════════════
   JOURNEY DATA — The Self-Discovery RPG
   ═══════════════════════════════════════════════════ */

export const TIERS = [
  {
    id: 1,
    name: 'The Awakening',
    subtitle: 'Discover your surface self',
    emoji: '🌱',
    description: 'Quick, fun, identity-affirming quizzes to get you started. Low barrier, big vibes.',
    gradient: 'linear-gradient(135deg, #98FF98, #64FFDA, #89CFF0)',
    glowColor: 'rgba(100, 255, 218, 0.4)',
    unlockReward: { tokens: 1, title: 'First Glimpse', description: 'AI gives a short synthesis of your identity so far' },
    bgAccent: '#64FFDA',
  },
  {
    id: 2,
    name: 'The Mirror',
    subtitle: 'Understand how you connect',
    emoji: '💫',
    description: 'Relationship & social self — how you love, fight, and show up for others.',
    gradient: 'linear-gradient(135deg, #FFB6C1, #E6BEFF, #C8A2FF)',
    glowColor: 'rgba(200, 162, 255, 0.4)',
    unlockReward: { tokens: 2, title: 'The Relationship Map', description: 'AI creates a deep analysis of your social patterns and attachment tendencies' },
    bgAccent: '#C8A2FF',
  },
  {
    id: 3,
    name: 'The Labyrinth',
    subtitle: 'Map your personality',
    emoji: '🔮',
    description: 'Established psychology frameworks — the real science behind who you are.',
    gradient: 'linear-gradient(135deg, #89CFF0, #A8A2FF, #C8A2FF)',
    glowColor: 'rgba(137, 207, 240, 0.4)',
    unlockReward: { tokens: 3, title: 'The Personality Blueprint', description: 'AI cross-references all personality frameworks to find your unique type cocktail' },
    bgAccent: '#89CFF0',
  },
  {
    id: 4,
    name: 'The Depths',
    subtitle: 'Explore your inner world',
    emoji: '🌊',
    description: 'Emotional intelligence, values, and what truly drives your decisions.',
    gradient: 'linear-gradient(135deg, #FFD700, #FFB366, #FF9999)',
    glowColor: 'rgba(255, 215, 0, 0.4)',
    unlockReward: { tokens: 5, title: 'The Inner Compass', description: 'AI maps your decision-making framework, moral compass, and emotional patterns' },
    bgAccent: '#FFD700',
  },
  {
    id: 5,
    name: 'The Shadow',
    subtitle: 'Confront your hidden self',
    emoji: '🌑',
    description: 'Deep psychology — the uncomfortable, transformative, life-changing stuff.',
    gradient: 'linear-gradient(135deg, #FF6B8A, #C8A2FF, #4B0082)',
    glowColor: 'rgba(255, 107, 138, 0.4)',
    unlockReward: { tokens: 10, title: 'The Deep Research', description: 'Full synthesis of ALL quiz data into a comprehensive multi-page personality report' },
    bgAccent: '#FF6B8A',
  },
];

export const QUIZZES = [
  // ── TIER 1: The Awakening ──────────────────────────
  {
    id: 'zodiac',
    tier: 1,
    order: 1,
    title: 'Zodiac Profile',
    subtitle: 'The stars already know',
    emoji: '♈',
    description: 'Enter your birthday and discover your Sun, Moon, and Rising signs — the cosmic foundation of who you are.',
    estimatedTime: '1 min',
    questionCount: 'Input',
    gradient: 'linear-gradient(135deg, #FFD700, #FFA500, #FF6B8A)',
    path: '/quiz/zodiac',
    available: true,
    completed: false,
  },
  {
    id: 'element',
    tier: 1,
    order: 2,
    title: 'Element Affinity',
    subtitle: 'Fire, water, earth, or air?',
    emoji: '🔥',
    description: 'Discover which classical element resonates with your spirit and shapes your energy.',
    estimatedTime: '2 min',
    questionCount: '10',
    gradient: 'linear-gradient(135deg, #FF6B00, #FF4444, #FFD700)',
    path: '/quiz/element',
    available: true,
    completed: false,
  },
  {
    id: 'aura',
    tier: 1,
    order: 3,
    title: 'Aura Quiz',
    subtitle: 'Discover your energy color',
    emoji: '🔮',
    description: 'Uncover which of 14 aura colors defines your personality through 98 soul-searching questions.',
    estimatedTime: '15 min',
    questionCount: '98',
    gradient: 'linear-gradient(135deg, #FFB6C1, #E6BEFF, #89CFF0)',
    path: '/aura/quiz',
    available: true,
    completed: false,
  },
  {
    id: 'color-personality',
    tier: 1,
    order: 4,
    title: 'Color Personality',
    subtitle: 'Your psyche in color',
    emoji: '🎨',
    description: 'Which color best represents the way your mind works and how you experience the world?',
    estimatedTime: '3 min',
    questionCount: '15',
    gradient: 'linear-gradient(135deg, #FF69B4, #FFD700, #64FFDA, #89CFF0)',
    path: '/quiz/color',
    available: true,
    completed: false,
  },
  {
    id: 'spirit-animal',
    tier: 1,
    order: 5,
    title: 'Spirit Animal',
    subtitle: 'What creature mirrors your soul?',
    emoji: '🦋',
    description: 'Find the animal archetype that mirrors your instincts, strengths, and hidden nature.',
    estimatedTime: '3 min',
    questionCount: '12',
    gradient: 'linear-gradient(135deg, #98FF98, #64FFDA, #89CFF0)',
    path: '/quiz/spirit-animal',
    available: true,
    completed: false,
  },

  // ── TIER 2: The Mirror ──────────────────────────────
  {
    id: 'love-language',
    tier: 2,
    order: 6,
    title: 'Love Language',
    subtitle: 'How you give and receive love',
    emoji: '💕',
    description: 'Discover whether words, touch, time, gifts, or acts of service speak loudest to your heart.',
    estimatedTime: '5 min',
    questionCount: '25',
    gradient: 'linear-gradient(135deg, #FF69B4, #FFB6C1, #E6BEFF)',
    path: '/quiz/love-language',
    available: true,
    completed: false,
  },
  {
    id: 'attachment',
    tier: 2,
    order: 7,
    title: 'Attachment Style',
    subtitle: 'Your relationship blueprint',
    emoji: '🔗',
    description: 'Are you secure, anxious, avoidant, or disorganized? Understanding this changes everything.',
    estimatedTime: '4 min',
    questionCount: '20',
    gradient: 'linear-gradient(135deg, #C8A2FF, #A8A2FF, #89CFF0)',
    path: '/quiz/attachment',
    available: true,
    completed: false,
  },
  {
    id: 'communication',
    tier: 2,
    order: 8,
    title: 'Communication Style',
    subtitle: 'How your words land',
    emoji: '💬',
    description: 'Assertive, passive, analytical, or expressive — discover how you naturally communicate.',
    estimatedTime: '4 min',
    questionCount: '18',
    gradient: 'linear-gradient(135deg, #89CFF0, #64FFDA, #98FF98)',
    path: '/quiz/communication',
    available: true,
    completed: false,
  },
  {
    id: 'conflict',
    tier: 2,
    order: 9,
    title: 'Conflict Style',
    subtitle: 'How you handle the heat',
    emoji: '⚔️',
    description: 'Do you fight, flee, freeze, or find a middle ground? Understand your conflict patterns.',
    estimatedTime: '4 min',
    questionCount: '18',
    gradient: 'linear-gradient(135deg, #FF9999, #FFB366, #FFD700)',
    path: '/quiz/conflict',
    available: true,
    completed: false,
  },
  {
    id: 'friendship',
    tier: 2,
    order: 10,
    title: 'Friendship Archetype',
    subtitle: 'Your role in the group',
    emoji: '👥',
    description: 'The protector, the adventurer, the listener, the spark — which archetype are you in friendships?',
    estimatedTime: '3 min',
    questionCount: '15',
    gradient: 'linear-gradient(135deg, #FFBCD9, #E6BEFF, #C8A2FF)',
    path: '/quiz/friendship',
    available: true,
    completed: false,
  },

  // ── TIER 3: The Labyrinth ──────────────────────────
  {
    id: 'enneagram',
    tier: 3,
    order: 11,
    title: 'Enneagram',
    subtitle: 'Your core motivation',
    emoji: '🔢',
    description: 'Discover your Enneagram type and wing — the deepest driver behind your personality.',
    estimatedTime: '8 min',
    questionCount: '40',
    gradient: 'linear-gradient(135deg, #C8A2FF, #A8A2FF, #89CFF0)',
    path: '/quiz/enneagram',
    available: true,
    completed: false,
  },
  {
    id: 'disc',
    tier: 3,
    order: 12,
    title: 'DISC Profile',
    subtitle: 'Your behavioral style',
    emoji: '📊',
    description: 'Map your Dominance, Influence, Steadiness, and Conscientiousness profile.',
    estimatedTime: '6 min',
    questionCount: '28',
    gradient: 'linear-gradient(135deg, #64FFDA, #89CFF0, #A8A2FF)',
    path: '/quiz/disc',
    available: true,
    completed: false,
  },
  {
    id: 'big5',
    tier: 3,
    order: 13,
    title: 'Big Five (OCEAN)',
    subtitle: 'The gold standard',
    emoji: '🧠',
    description: 'Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism — the Big Five.',
    estimatedTime: '10 min',
    questionCount: '50',
    gradient: 'linear-gradient(135deg, #89CFF0, #64FFDA, #98FF98)',
    path: '/quiz/big5',
    available: true,
    completed: false,
  },
  {
    id: 'mbti',
    tier: 3,
    order: 14,
    title: 'Myers-Briggs',
    subtitle: 'Your 4-letter type',
    emoji: '🧩',
    description: 'INFJ? ENTP? Discover your Myers-Briggs type across 16 possible personalities.',
    estimatedTime: '12 min',
    questionCount: '64',
    gradient: 'linear-gradient(135deg, #E6BEFF, #C8A2FF, #FF69B4)',
    path: '/quiz/mbti',
    available: true,
    completed: false,
  },
  {
    id: 'temperament',
    tier: 3,
    order: 15,
    title: 'Temperament',
    subtitle: 'Your ancient nature',
    emoji: '🏛️',
    description: 'Sanguine, choleric, melancholic, or phlegmatic — the oldest personality framework.',
    estimatedTime: '5 min',
    questionCount: '24',
    gradient: 'linear-gradient(135deg, #FFB6C1, #FFDAB9, #FFD700)',
    path: '/quiz/temperament',
    available: true,
    completed: false,
  },

  // ── TIER 4: The Depths ──────────────────────────────
  {
    id: 'eq',
    tier: 4,
    order: 16,
    title: 'Emotional Intelligence',
    subtitle: 'Your EQ score',
    emoji: '❤️‍🔥',
    description: 'Measure your self-awareness, empathy, emotional regulation, and social skills.',
    estimatedTime: '10 min',
    questionCount: '36',
    gradient: 'linear-gradient(135deg, #FF6B8A, #FFB6C1, #E6BEFF)',
    path: '/quiz/eq',
    available: true,
    completed: false,
  },
  {
    id: 'values',
    tier: 4,
    order: 17,
    title: 'Core Values',
    subtitle: 'What drives your decisions',
    emoji: '💎',
    description: 'Rank and discover the top 5 values that silently steer every choice you make.',
    estimatedTime: '8 min',
    questionCount: '30',
    gradient: 'linear-gradient(135deg, #FFD700, #64FFDA, #89CFF0)',
    path: '/quiz/values',
    available: true,
    completed: false,
  },
  {
    id: 'moral',
    tier: 4,
    order: 18,
    title: 'Moral Foundations',
    subtitle: 'Your ethical compass',
    emoji: '⚖️',
    description: 'Care, fairness, loyalty, authority, purity, liberty — which moral foundations guide you?',
    estimatedTime: '8 min',
    questionCount: '30',
    gradient: 'linear-gradient(135deg, #C8A2FF, #89CFF0, #64FFDA)',
    path: '/quiz/moral',
    available: true,
    completed: false,
  },
  {
    id: 'strengths',
    tier: 4,
    order: 19,
    title: 'Strengths Finder',
    subtitle: 'Your natural talents',
    emoji: '💪',
    description: 'Identify your top 5 innate strengths and learn how to leverage them.',
    estimatedTime: '10 min',
    questionCount: '38',
    gradient: 'linear-gradient(135deg, #FFB366, #FFD700, #98FF98)',
    path: '/quiz/strengths',
    available: true,
    completed: false,
  },
  {
    id: 'cognitive',
    tier: 4,
    order: 20,
    title: 'Cognitive Style',
    subtitle: 'How your brain works',
    emoji: '🧬',
    description: 'Visual, verbal, analytical, intuitive — discover how you naturally think and learn.',
    estimatedTime: '7 min',
    questionCount: '28',
    gradient: 'linear-gradient(135deg, #89CFF0, #A8A2FF, #E6BEFF)',
    path: '/quiz/cognitive',
    available: true,
    completed: false,
  },

  // ── TIER 5: The Shadow ──────────────────────────────
  {
    id: 'jungian',
    tier: 5,
    order: 21,
    title: 'Jungian Archetypes',
    subtitle: 'Your mythic identity',
    emoji: '🎭',
    description: 'Hero, shadow, anima/animus, sage, trickster — which Jungian archetypes live within you?',
    estimatedTime: '15 min',
    questionCount: '48',
    gradient: 'linear-gradient(135deg, #4B0082, #C8A2FF, #FF6B8A)',
    path: '/quiz/jungian',
    available: true,
    completed: false,
  },
  {
    id: 'defense',
    tier: 5,
    order: 22,
    title: 'Defense Mechanisms',
    subtitle: 'How you protect yourself',
    emoji: '🛡️',
    description: 'Denial, projection, humor, sublimation — discover the shields your psyche uses.',
    estimatedTime: '10 min',
    questionCount: '30',
    gradient: 'linear-gradient(135deg, #8A8A8A, #C8A2FF, #89CFF0)',
    path: '/quiz/defense',
    available: true,
    completed: false,
  },
  {
    id: 'fear',
    tier: 5,
    order: 23,
    title: 'Fear Profile',
    subtitle: 'The root of your avoidance',
    emoji: '👁️',
    description: 'What root fears silently drive your behavior, decisions, and self-sabotage patterns?',
    estimatedTime: '10 min',
    questionCount: '28',
    gradient: 'linear-gradient(135deg, #1a0a3e, #4B0082, #FF6B8A)',
    path: '/quiz/fear',
    available: true,
    completed: false,
  },
  {
    id: 'narrative',
    tier: 5,
    order: 24,
    title: 'Life Narrative',
    subtitle: 'The story you tell yourself',
    emoji: '📖',
    description: 'Uncover the narrative arc you\'ve unconsciously written for your life — and whether it serves you.',
    estimatedTime: '15 min',
    questionCount: '25+',
    gradient: 'linear-gradient(135deg, #FFB6C1, #4B0082, #0d0221)',
    path: '/quiz/narrative',
    available: true,
    completed: false,
  },
  {
    id: 'shadow',
    tier: 5,
    order: 25,
    title: 'Shadow Self',
    subtitle: 'Meet your other half',
    emoji: '🌑',
    description: 'Confront the repressed traits, hidden desires, and blind spots that shape you from the dark.',
    estimatedTime: '20 min',
    questionCount: '40',
    gradient: 'linear-gradient(135deg, #0d0221, #4B0082, #FF6B8A, #FFD700)',
    path: '/quiz/shadow',
    available: true,
    completed: false,
  },
];

/* Helper to get quizzes for a specific tier */
export function getQuizzesByTier(tierId) {
  return QUIZZES.filter((q) => q.tier === tierId);
}

/* Helper to get tier data */
export function getTierById(tierId) {
  return TIERS.find((t) => t.id === tierId);
}
