// QuestionBank.js

// Define the common response options
const responseOptions = [
    "This does not describe me",
    "I am very seldom like this",
    "I am sometimes like this",
    "I am often like this",
    "This is me!",
];

// Define the questions
const qBank = [
    { id: 1, question: "You are methodical in your thinking.", options: responseOptions },
    { id: 2, question: "You have a strong inner desire to make your mark on the world.", options: responseOptions },
    { id: 3, question: "You resent emotional and domestic demands made on you.", options: responseOptions },
    { id: 4, question: "Esoteric spiritual or political philosophies have a great emotional and intellectual appeal for you.", options: responseOptions },
    { id: 5, question: "You seek the unusual or the avant-garde.", options: responseOptions },
    { id: 6, question: "You cry easily.", options: responseOptions },
    { id: 7, question: "You are not judgemental or critical of the ways in which others express their emotions or feelings.", options: responseOptions },
    { id: 8, question: "You are at ease in any environment where healing is the primary activity or occupation.", options: responseOptions },
    { id: 9, question: "When faced with a dangerous task, you carefully plan how to handle any crisis that may arise.", options: responseOptions },
    { id: 10, question: "You are a loner.", options: responseOptions },
    { id: 11, question: "When solving problems, you are able to visualize all the steps and the solution at the same time.", options: responseOptions },
    { id: 12, question: "You have no biases about sexuality, heterosexuality, bisexuality, or homosexuality.", options: responseOptions },
    { id: 13, question: "You prefer working at jobs that are physically demanding.", options: responseOptions },
    { id: 14, question: "You react physically (with sweaty palms, for example) before you respond to a situation mentally or emotionally.", options: responseOptions },
    { id: 15, question: "As a leader, you solicit lots of detailed information from others in order to make decisions.", options: responseOptions },
    { id: 16, question: "Social get-togethers such as cocktail parties bore you.", options: responseOptions },
    { id: 17, question: "You prefer occupations that have unlimited financial opportunity, such as sales.", options: responseOptions },
    { id: 18, question: "When you have money, you spend it; when you don't, you don't.", options: responseOptions },
    { id: 19, question: "You are a nonconformist.", options: responseOptions },
    { id: 20, question: "You have a hard time saying no when people ask you to do them a favor.", options: responseOptions },
    { id: 21, question: "You organize projects by creating systems.", options: responseOptions },
    { id: 22, question: "You depend on other people for clues on how you should act in various social situations.", options: responseOptions },
    { id: 23, question: "You meet physical challenges without fear.", options: responseOptions },
    { id: 24, question: "You are slow to choose friends.", options: responseOptions },
    { id: 25, question: "You do not require emotional loyalty to effectively mentor someone.", options: responseOptions },
    { id: 26, question: "In school, you learn most effectively in an unstructured environment.", options: responseOptions },
    { id: 27, question: "For you, sex is for physical pleasure.", options: responseOptions },
    { id: 28, question: "When you find yourself in a tense situation, you want to run away or pretend it does not exist.", options: responseOptions },
    { id: 29, question: "You have difficulty sharing your emotions and feelings with others.", options: responseOptions },
    { id: 30, question: "You would rather be the theorist of a project, and leave the building of the working model to someone else.", options: responseOptions },
    { id: 31, question: "You diagnose problems by recognizing patterns.", options: responseOptions },
    { id: 32, question: "You are a dreamer who likes to live in fantasies you create.", options: responseOptions },
    { id: 33, question: "You are a spontaneous person.", options: responseOptions },
    { id: 34, question: "The experience of God's love is the spiritual force in your life.", options: responseOptions },
    { id: 35, question: "You look for ways to improve your community.", options: responseOptions },
    { id: 36, question: "You rarely show your deepest feelings.", options: responseOptions },
    { id: 37, question: "You prefer activities that allow you to demonstrate physical prowess.", options: responseOptions },
    { id: 38, question: "You evaluate objects by how solid or substantial they feel.", options: responseOptions },
    { id: 39, question: "You are attracted to religions with strong theological structures that allow for personal interpretation.", options: responseOptions },
    { id: 40, question: "You lead by forcing others to rethink and reexamine old beliefs, values, and ways of doing things.", options: responseOptions },
    { id: 41, question: "When you lose your temper, you get over it quickly.", options: responseOptions },
    { id: 42, question: "You are not cynical.", options: responseOptions },
    { id: 43, question: "You like social activities that combine business and pleasure.", options: responseOptions },
    { id: 44, question: "You are not \"free and easy\" when spending your money on others.", options: responseOptions },
    { id: 45, question: "You see God as the \"brain\" that created the universe.", options: responseOptions },
    { id: 46, question: "You express your sexuality creatively, intuitively, and experimentally.", options: responseOptions },
    { id: 47, question: "You are attracted to products that have unusual or unexpected design features.", options: responseOptions },
    { id: 48, question: "When looking for a job, you have difficulty asking for the salary you deserve.", options: responseOptions },
    { id: 49, question: "You feel that raising a well-educated child is the greatest contribution you can make to your community.", options: responseOptions },
    { id: 50, question: "You enjoy reading biographies and diaries that describe the lives of real people.", options: responseOptions },
    { id: 51, question: "You prefer individual competition rather than team effort.", options: responseOptions },
    { id: 52, question: "You are slow to commit to any belief system.", options: responseOptions },
    { id: 53, question: "You eagerly seek to please those you love and care about.", options: responseOptions },
    { id: 54, question: "You perceive spirituality to be in everything you do.", options: responseOptions },
    { id: 55, question: "If you have enough money to buy the necessities, you are happy.", options: responseOptions },
    { id: 56, question: "You experience God as the physical sensation of the joy of being alive.", options: responseOptions },
    { id: 57, question: "You prefer a spiritual belief system that relies on a foundation of laws and principles.", options: responseOptions },
    { id: 58, question: "You lead by telling people what to do.", options: responseOptions },
    { id: 59, question: "You prefer a few specially chosen friends who stimulate you intellectually.", options: responseOptions },
    { id: 60, question: "Your artistic pursuits often keep you indoors.", options: responseOptions },
    { id: 61, question: "You form loose friendships that are not encumbered with bonds of expectation.", options: responseOptions },
    { id: 62, question: "You feel more comfortable sharing the leadership by being co-chairperson.", options: responseOptions },
    { id: 63, question: "You financially support community groups and programs that benefit society.", options: responseOptions },
    { id: 64, question: "Your source of personal power is your ability to mentally retreat inward.", options: responseOptions },
    { id: 65, question: "You are not interested in organized religion or other belief systems.", options: responseOptions },
    { id: 66, question: "You are meticulous in following instructions given to you by your supervisor.", options: responseOptions },
    { id: 67, question: "You prefer social gatherings where you have an opportunity to talk to many different people.", options: responseOptions },
    { id: 68, question: "You need to be awakened slowly from a sound sleep to avoid being irritable or in physical pain.", options: responseOptions },
    { id: 69, question: "When playing a team sport, you rally the team when the chips are down.", options: responseOptions },
    { id: 70, question: "You like parties.", options: responseOptions },
    { id: 71, question: "To you, money is security.", options: responseOptions },
    { id: 72, question: "You feel compelled to do something significant with your life.", options: responseOptions },
    { id: 73, question: "You find great satisfaction in assisting people by giving ideas and information.", options: responseOptions },
    { id: 74, question: "You prefer a somewhat isolated existence rather than one in which you would have to conform to society's expectations.", options: responseOptions },
    { id: 75, question: "When you see something that you like, you choose to have your fantasy now and pay later.", options: responseOptions },
    { id: 76, question: "You do not enjoy endurance sports such as cross-country running, skiing or weight-lifting.", options: responseOptions },
    { id: 77, question: "You feel that spiritual principles must have practical application in the real world.", options: responseOptions },
    { id: 78, question: "You prefer quiet, introspective, spiritual disciplines.", options: responseOptions },
    { id: 79, question: "You prefer to work for a commission, or even as a freelancer, rather than for a regular, fixed salary.", options: responseOptions },
    { id: 80, question: "You believe that to be a good leader, you must first be a good follower.", options: responseOptions },
    { id: 81, question: "You have difficulty managing money effectively.", options: responseOptions },
    { id: 82, question: "You cannot be coerced into doing something in which you are not interested.", options: responseOptions },
    { id: 83, question: "You experience spirituality when you physically participate in a worship service.", options: responseOptions },
    { id: 84, question: "You lead others with enthusiasm because you enjoy being with people.", options: responseOptions },
    { id: 85, question: "You enjoy working with mechanical devices such as computers, calculators, and stereo equipment.", options: responseOptions },
    { id: 86, question: "Possessions are important to you as stepping-stones to power and influence.", options: responseOptions },
    { id: 87, question: "To you, ideas are things, not mental abstractions.", options: responseOptions },
    { id: 88, question: "You see ideas as three-dimensional patterns.", options: responseOptions },
    { id: 89, question: "You express your spirituality through your strong connection with nature.", options: responseOptions },
    { id: 90, question: "When making a decision, you try to find a solution that will please everyone.", options: responseOptions },
    { id: 91, question: "You lead others by incorporating their feelings into the decision-making process.", options: responseOptions },
    { id: 92, question: "You work best in an environment that is calm and peaceful with limited contact with others.", options: responseOptions },
    { id: 93, question: "You do not need friends or social interaction to be happy.", options: responseOptions },
    { id: 94, question: "To you, money represents physical safety and stability.", options: responseOptions },
    { id: 95, question: "You have difficulty keeping track of personal possessions.", options: responseOptions },
    { id: 96, question: "You are content to work with your hands.", options: responseOptions },
    { id: 97, question: "You want to know how and why things work the way they do.", options: responseOptions },
    { id: 98, question: "You enjoy working in occupations that require physical activity.", options: responseOptions },
];

export default qBank;
